name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: |
          npm install -g @capacitor/cli
          npm install

      - name: Initialize Capacitor & Android
        run: |
          npx cap init "Alphabet Game" "com.example.alphabet" --web-dir=.
          npx cap add android

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: alphabet-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
